import type { RawProperty } from "@/types";

export const SAMPLE_PROPERTIES: RawProperty[] = [
  {
    name: "【サンプル】大阪市浪速区 木造アパート",
    price: 5800 * 10000,
    address: "大阪府大阪市浪速区難波中2丁目",
    landArea: 82.5,
    buildingArea: 148.2,
    floorPlan: "1R×8",
    structure: "木造",
    builtYear: 1998,
    builtMonth: 3,
    zoning: "商業地域",
    buildingCoverageRatio: 80,
    floorAreaRatio: 400,
    roadContact: "1面",
    frontRoadWidth: 4,
    canRebuild: true,
    setback: false,
    nearestStation: "大阪メトロ難波駅",
    walkMinutes: 7,
    assumedRent: 55 * 10000,
    grossYield: 11.4 / 100,
    currentUrl: "https://example.com/sample1",
    detailUrl: "https://example.com/sample1",
    source: "manual",
    fetchedAt: new Date().toISOString(),
  },
  {
    name: "【サンプル】東京都足立区 RC区分",
    price: 3200 * 10000,
    address: "東京都足立区西新井1丁目",
    landArea: 45.0,
    buildingArea: 62.5,
    floorPlan: "2LDK",
    structure: "RC",
    builtYear: 2005,
    builtMonth: 10,
    zoning: "第一種住居地域",
    buildingCoverageRatio: 60,
    floorAreaRatio: 200,
    roadContact: "1面",
    frontRoadWidth: 6,
    canRebuild: true,
    setback: false,
    nearestStation: "東武伊勢崎線西新井駅",
    walkMinutes: 5,
    assumedRent: 18 * 10000,
    grossYield: 6.75 / 100,
    currentUrl: "https://example.com/sample2",
    detailUrl: "https://example.com/sample2",
    source: "manual",
    fetchedAt: new Date().toISOString(),
  },
  {
    name: "【サンプル】福岡市博多区 軽鉄一棟",
    price: 8500 * 10000,
    address: "福岡県福岡市博多区博多駅東3丁目",
    landArea: 120.0,
    buildingArea: 210.0,
    floorPlan: "1K×12",
    structure: "軽量鉄骨",
    builtYear: 2002,
    builtMonth: 6,
    zoning: "近隣商業地域",
    buildingCoverageRatio: 80,
    floorAreaRatio: 300,
    roadContact: "2面以上",
    frontRoadWidth: 6,
    canRebuild: true,
    setback: false,
    nearestStation: "JR博多駅",
    walkMinutes: 8,
    assumedRent: 80 * 10000,
    grossYield: 11.3 / 100,
    currentUrl: "https://example.com/sample3",
    detailUrl: "https://example.com/sample3",
    source: "manual",
    fetchedAt: new Date().toISOString(),
  },
];
